import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "@/lib/appProviders";
import Container from "@/components/common/Container";
import Navbar from "@/components/common/navbar";
import { Toaster } from "@/components/ui/sonner";
import ThemeProvider from "@/lib/themeProvider";
import Footer from "@/components/common/footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
  icons: { icon: "/rick-icon.svg" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased bg-[#ededed] dark:bg-[#272b33] `}
      >
        <Providers>
          <ThemeProvider>
            <Navbar />
            <Toaster />
            <Container>{children}</Container>
            <Footer />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
